#!/bin/sh
#---------------------------------#
#  pre-requirements configuration #
#---------------------------------#

echo -e
echo -e "========================================"
echo -e "Pre-requirements"
echo -e "========================================"
echo -e
dotnet tool install -g Cake.Tool --version 0.30.0


#---------------------------------#
#      pipeline configuration     #
#---------------------------------#

dotnet cake || exit 1
echo -e
echo -e "========================================"
echo -e "Commit"
echo -e "========================================"
echo -e