language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2

branches:
  only:
    - master

install:
  - dotnet tool install -g Cake.Tool --version 0.30.0
  - export PATH=$PATH:$HOME/.dotnet/tools

script:
  - dotnet-cake