language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
branches:
  only:
   - master
install:
 - dotnet restore
script:
 - dotnet build -c Release
 - dotnet test -c Release test/unit/Http.Query.Filter.Test/Http.Query.Filter.Test.csproj
 - dotnet test -c Release test/unit/Http.Query.Filter.Client.Test/Http.Query.Filter.Client.Test.csproj
 - dotnet test -c Release test/integration/Http.Query.Filter.Integration.Test/Http.Query.Filter.Integration.Test.csproj