# Reference: https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '.{build}'

branches:
  only:
    - master

skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  nuget_key:
    secure: NxNpeauRwvVn3Uvt3UPyB2a+n4og2WWv9x4527DbKy3UomugXXZjGfqwr3IE6hVp
  nuget_url: https://www.nuget.org/api/v2/package

pull_requests:
  do_not_increment_build_number: true



#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - Release

before_build:
  - dotnet restore

build_script:
  - dotnet build -c %CONFIGURATION%
  - dotnet pack src\Http.Query.Filter\Http.Query.Filter.csproj -c %CONFIGURATION% --version-suffix "%APPVEYOR_BUILD_VERSION%"
  - dotnet pack src\Http.Query.Filter.Client\Http.Query.Filter.Client.csproj -c %CONFIGURATION% --version-suffix "%APPVEYOR_BUILD_VERSION%"
  - dotnet nuget push src\Http.Query.Filter\bin\%CONFIGURATION%\*.nupkg -s %nuget_url% -k %nuget_key%
  - dotnet nuget push src\Http.Query.Filter.Client\bin\%CONFIGURATION%\*.nupkg -s %nuget_url% -k %nuget_key%


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - dotnet test -c %CONFIGURATION% test\unit\Http.Query.Filter.Test\Http.Query.Filter.Test.csproj
  - dotnet test -c %CONFIGURATION% test\unit\Http.Query.Filter.Client.Test\Http.Query.Filter.Client.Test.csproj
  - dotnet test -c %CONFIGURATION% test\integration\Http.Query.Filter.Integration.Test\Http.Query.Filter.Integration.Test.csproj