# Reference: https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '.{build}'

branches:
  only:
    - master

skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

pull_requests:
  do_not_increment_build_number: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - Release

install:
  - cmd: dotnet tool install -g Cake.Tool --version 0.30.0

build_script:
  - cmd: dotnet cake

after_build:
  - dotnet pack src\Http.Query.Filter\Http.Query.Filter.csproj -c %CONFIGURATION% --version-suffix "%APPVEYOR_BUILD_VERSION%"
  - dotnet pack src\Http.Query.Filter.Client\Http.Query.Filter.Client.csproj -c %CONFIGURATION% --version-suffix "%APPVEYOR_BUILD_VERSION%"


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'
    name: packages


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: c+t+t7j+Y2QtAhLm35+YbZB+IFaMN+a77YPT8a/jKz7Y3t7OAk0LBCbIKqJwurRk
    on:
      branch: master
    artifact: packages